# Configuration file for machine-status client

# Where are we checking free space?
mountpoint = "/"

# How little free space before we warn?
min_free_space = 20

# How high is too high for load averages?
max_load_avg = 3

# Server IP. Default 127.0.0.1 (localhost)
machine_status_ip = "127.0.0.1"

# Server web port. Default is 80
machine_status_port = 8080
