/*
 * Machine status API
 *
 * Helps to track status of networked machines.
 *
 * API version: 0.1
 * Contact: awball@polarweasel.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

type Route struct {
	Name        string
	Method      string
	Pattern     string
	HandlerFunc http.HandlerFunc
}

type Routes []Route

func NewRouter() *mux.Router {
	router := mux.NewRouter().StrictSlash(true)
	for _, route := range routes {
		var handler http.Handler
		handler = route.HandlerFunc
		handler = Logger(handler, route.Name)

		router.
			Methods(route.Method).
			Path(route.Pattern).
			Name(route.Name).
			Handler(handler)
	}

	return router
}

func Index(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "Hello World!")
}

var routes = Routes{
	//	Route{
	//		"Index",
	//		"GET",
	//		"/machine-status/",
	//		Index,
	//	},

	Route{
		"APIVersionList",
		strings.ToUpper("Get"),
		"/machine-status/",
		APIVersionList,
	},

	Route{
		"GetAllMachines",
		strings.ToUpper("Get"),
		"/machine-status/machines",
		GetAllMachines,
	},

	Route{
		"GetMachine",
		strings.ToUpper("Get"),
		"/machine-status/machines/{machineId}",
		GetMachine,
	},

	Route{
		"UpdateMachine",
		strings.ToUpper("Put"),
		"/machine-status/machines/{machineId}",
		UpdateMachine,
	},

	Route{
		"VibeCheck",
		strings.ToUpper("Get"),
		"/machine-status/vibe",
		VibeCheck,
	},
}
