# coding: utf-8

"""
    Machine status API

    Helps to track status of networked machines.  # noqa: E501

    OpenAPI spec version: 0.1
    Contact: awball@polarweasel.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.machine_name import MachineName  # noqa: E501
from swagger_client.rest import ApiException


class TestMachineName(unittest.TestCase):
    """MachineName unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMachineName(self):
        """Test MachineName"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.machine_name.MachineName()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
