# coding: utf-8

"""
    Machine status API

    Helps to track status of networked machines.  # noqa: E501

    OpenAPI spec version: 0.1
    Contact: awball@polarweasel.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.api_info_api import APIInfoApi  # noqa: E501
from swagger_client.rest import ApiException


class TestAPIInfoApi(unittest.TestCase):
    """APIInfoApi unit test stubs"""

    def setUp(self):
        self.api = APIInfoApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_a_pi_version_list(self):
        """Test case for a_pi_version_list

        Get API version  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
