/*
 * Machine status API
 *
 * Helps to track status of networked machines.
 *
 * API version: 0.1
 * Contact: awball@polarweasel.org
 * Initial code generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package main

import (
	"log"
	"net/http"

	sw "polarweasel/machine-updates/go"
)

const APIVersion string = "0.1"

func main() {
	log.Printf("Server started on port 8080, API version %s", APIVersion)

	router := sw.NewRouter()

	log.Fatal(http.ListenAndServe(":8080", router))
}
