/*
 * Machine status API
 *
 * Helps to track status of networked machines.
 *
 * API version: 0.1
 * Contact: awball@polarweasel.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type DiskFreeFreeSpace struct {
	// Available disk space, as an integer percentage
	FreeSpacePercentage int32 `json:"freeSpacePercentage,omitempty"`
	// True if this should be highlighted, false otherwise
	ProblemFlag bool `json:"problemFlag,omitempty"`
}
