/*
 * Machine status API
 *
 * Helps to track status of networked machines.
 *
 * API version: 0.1
 * Contact: awball@polarweasel.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Free space on a machine's main mount of interest.
type DiskFree struct {

	MountPoint string `json:"mountPoint,omitempty"`

	FreeSpace *DiskFreeFreeSpace `json:"freeSpace,omitempty"`
}
