/*
 * Machine status API
 *
 * Helps to track status of networked machines.
 *
 * API version: 0.1
 * Contact: awball@polarweasel.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// A machine's 1/5/15-minute load averages
type LoadAverages struct {

	Load1 float64 `json:"load-1,omitempty"`

	Load5 float64 `json:"load-5,omitempty"`

	Load15 float64 `json:"load-15,omitempty"`
	// True if this should be highlighted, false otherwise
	ProblemFlag bool `json:"problemFlag,omitempty"`
}
