/*
 * Machine status API
 *
 * Helps to track status of networked machines.
 *
 * API version: 0.1
 * Contact: awball@polarweasel.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type MachineMachineStatus struct {

	LoadAverages *LoadAverages `json:"loadAverages,omitempty"`

	DiskFree *DiskFree `json:"diskFree,omitempty"`
}
