/*
 * Machine status API
 *
 * Helps to track status of networked machines.
 *
 * API version: 0.1
 * Contact: awball@polarweasel.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type InlineResponse2001 struct {

	OverallVibe string `json:"overall-vibe,omitempty"`
}
