/*
 * Machine status API
 *
 * Helps to track status of networked machines.
 *
 * API version: 0.1
 * Contact: awball@polarweasel.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Machine struct {

	Name string `json:"name,omitempty"`
	// Optional description of the machine (not useful in a small UI)
	MachineDescription string `json:"machineDescription,omitempty"`

	MachineStatus *MachineMachineStatus `json:"machineStatus,omitempty"`
}
