# coding: utf-8

# flake8: noqa
"""
    Machine status API

    Helps to track status of networked machines.  # noqa: E501

    OpenAPI spec version: 0.1
    Contact: awball@polarweasel.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import models into model package
from swagger_client.models.disk_free import DiskFree
from swagger_client.models.disk_free_free_space import DiskFreeFreeSpace
from swagger_client.models.error_response import ErrorResponse
from swagger_client.models.inline_response200 import InlineResponse200
from swagger_client.models.inline_response2001 import InlineResponse2001
from swagger_client.models.load_averages import LoadAverages
from swagger_client.models.machine import Machine
from swagger_client.models.machine_collection import MachineCollection
from swagger_client.models.machine_machine_status import MachineMachineStatus
from swagger_client.models.machine_name import MachineName
