# coding: utf-8

"""
    Machine status API

    Helps to track status of networked machines.  # noqa: E501

    OpenAPI spec version: 0.1
    Contact: awball@polarweasel.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class InlineResponse2001(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'overall_vibe': 'str'
    }

    attribute_map = {
        'overall_vibe': 'overall-vibe'
    }

    def __init__(self, overall_vibe=None):  # noqa: E501
        """InlineResponse2001 - a model defined in Swagger"""  # noqa: E501
        self._overall_vibe = None
        self.discriminator = None
        if overall_vibe is not None:
            self.overall_vibe = overall_vibe

    @property
    def overall_vibe(self):
        """Gets the overall_vibe of this InlineResponse2001.  # noqa: E501


        :return: The overall_vibe of this InlineResponse2001.  # noqa: E501
        :rtype: str
        """
        return self._overall_vibe

    @overall_vibe.setter
    def overall_vibe(self, overall_vibe):
        """Sets the overall_vibe of this InlineResponse2001.


        :param overall_vibe: The overall_vibe of this InlineResponse2001.  # noqa: E501
        :type: str
        """
        allowed_values = ["happy", "missing-machine", "oh-shit"]  # noqa: E501
        if overall_vibe not in allowed_values:
            raise ValueError(
                "Invalid value for `overall_vibe` ({0}), must be one of {1}"  # noqa: E501
                .format(overall_vibe, allowed_values)
            )

        self._overall_vibe = overall_vibe

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InlineResponse2001, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse2001):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
