# coding: utf-8

"""
    Machine status API

    Helps to track status of networked machines.  # noqa: E501

    OpenAPI spec version: 0.1
    Contact: awball@polarweasel.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class MachineMachineStatus(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'load_averages': 'LoadAverages',
        'disk_free': 'DiskFree'
    }

    attribute_map = {
        'load_averages': 'loadAverages',
        'disk_free': 'diskFree'
    }

    def __init__(self, load_averages=None, disk_free=None):  # noqa: E501
        """MachineMachineStatus - a model defined in Swagger"""  # noqa: E501
        self._load_averages = None
        self._disk_free = None
        self.discriminator = None
        if load_averages is not None:
            self.load_averages = load_averages
        if disk_free is not None:
            self.disk_free = disk_free

    @property
    def load_averages(self):
        """Gets the load_averages of this MachineMachineStatus.  # noqa: E501


        :return: The load_averages of this MachineMachineStatus.  # noqa: E501
        :rtype: LoadAverages
        """
        return self._load_averages

    @load_averages.setter
    def load_averages(self, load_averages):
        """Sets the load_averages of this MachineMachineStatus.


        :param load_averages: The load_averages of this MachineMachineStatus.  # noqa: E501
        :type: LoadAverages
        """

        self._load_averages = load_averages

    @property
    def disk_free(self):
        """Gets the disk_free of this MachineMachineStatus.  # noqa: E501


        :return: The disk_free of this MachineMachineStatus.  # noqa: E501
        :rtype: DiskFree
        """
        return self._disk_free

    @disk_free.setter
    def disk_free(self, disk_free):
        """Sets the disk_free of this MachineMachineStatus.


        :param disk_free: The disk_free of this MachineMachineStatus.  # noqa: E501
        :type: DiskFree
        """

        self._disk_free = disk_free

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(MachineMachineStatus, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, MachineMachineStatus):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
