# coding: utf-8

"""
    Machine status API

    Helps to track status of networked machines.  # noqa: E501

    OpenAPI spec version: 0.1
    Contact: awball@polarweasel.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class DiskFree(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'mount_point': 'str',
        'free_space': 'DiskFreeFreeSpace'
    }

    attribute_map = {
        'mount_point': 'mountPoint',
        'free_space': 'freeSpace'
    }

    def __init__(self, mount_point=None, free_space=None):  # noqa: E501
        """DiskFree - a model defined in Swagger"""  # noqa: E501
        self._mount_point = None
        self._free_space = None
        self.discriminator = None
        if mount_point is not None:
            self.mount_point = mount_point
        if free_space is not None:
            self.free_space = free_space

    @property
    def mount_point(self):
        """Gets the mount_point of this DiskFree.  # noqa: E501


        :return: The mount_point of this DiskFree.  # noqa: E501
        :rtype: str
        """
        return self._mount_point

    @mount_point.setter
    def mount_point(self, mount_point):
        """Sets the mount_point of this DiskFree.


        :param mount_point: The mount_point of this DiskFree.  # noqa: E501
        :type: str
        """

        self._mount_point = mount_point

    @property
    def free_space(self):
        """Gets the free_space of this DiskFree.  # noqa: E501


        :return: The free_space of this DiskFree.  # noqa: E501
        :rtype: DiskFreeFreeSpace
        """
        return self._free_space

    @free_space.setter
    def free_space(self, free_space):
        """Sets the free_space of this DiskFree.


        :param free_space: The free_space of this DiskFree.  # noqa: E501
        :type: DiskFreeFreeSpace
        """

        self._free_space = free_space

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(DiskFree, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DiskFree):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
