# coding: utf-8

"""
    Machine status API

    Helps to track status of networked machines.  # noqa: E501

    OpenAPI spec version: 0.1
    Contact: awball@polarweasel.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class LoadAverages(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'load_1': 'float',
        'load_5': 'float',
        'load_15': 'float',
        'problem_flag': 'bool'
    }

    attribute_map = {
        'load_1': 'load-1',
        'load_5': 'load-5',
        'load_15': 'load-15',
        'problem_flag': 'problemFlag'
    }

    def __init__(self, load_1=None, load_5=None, load_15=None, problem_flag=False):  # noqa: E501
        """LoadAverages - a model defined in Swagger"""  # noqa: E501
        self._load_1 = None
        self._load_5 = None
        self._load_15 = None
        self._problem_flag = None
        self.discriminator = None
        if load_1 is not None:
            self.load_1 = load_1
        if load_5 is not None:
            self.load_5 = load_5
        if load_15 is not None:
            self.load_15 = load_15
        if problem_flag is not None:
            self.problem_flag = problem_flag

    @property
    def load_1(self):
        """Gets the load_1 of this LoadAverages.  # noqa: E501


        :return: The load_1 of this LoadAverages.  # noqa: E501
        :rtype: float
        """
        return self._load_1

    @load_1.setter
    def load_1(self, load_1):
        """Sets the load_1 of this LoadAverages.


        :param load_1: The load_1 of this LoadAverages.  # noqa: E501
        :type: float
        """

        self._load_1 = load_1

    @property
    def load_5(self):
        """Gets the load_5 of this LoadAverages.  # noqa: E501


        :return: The load_5 of this LoadAverages.  # noqa: E501
        :rtype: float
        """
        return self._load_5

    @load_5.setter
    def load_5(self, load_5):
        """Sets the load_5 of this LoadAverages.


        :param load_5: The load_5 of this LoadAverages.  # noqa: E501
        :type: float
        """

        self._load_5 = load_5

    @property
    def load_15(self):
        """Gets the load_15 of this LoadAverages.  # noqa: E501


        :return: The load_15 of this LoadAverages.  # noqa: E501
        :rtype: float
        """
        return self._load_15

    @load_15.setter
    def load_15(self, load_15):
        """Sets the load_15 of this LoadAverages.


        :param load_15: The load_15 of this LoadAverages.  # noqa: E501
        :type: float
        """

        self._load_15 = load_15

    @property
    def problem_flag(self):
        """Gets the problem_flag of this LoadAverages.  # noqa: E501

        True if this should be highlighted, false otherwise  # noqa: E501

        :return: The problem_flag of this LoadAverages.  # noqa: E501
        :rtype: bool
        """
        return self._problem_flag

    @problem_flag.setter
    def problem_flag(self, problem_flag):
        """Sets the problem_flag of this LoadAverages.

        True if this should be highlighted, false otherwise  # noqa: E501

        :param problem_flag: The problem_flag of this LoadAverages.  # noqa: E501
        :type: bool
        """

        self._problem_flag = problem_flag

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(LoadAverages, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, LoadAverages):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
