# coding: utf-8

"""
    Machine status API

    Helps to track status of networked machines.  # noqa: E501

    OpenAPI spec version: 0.1
    Contact: awball@polarweasel.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.machine_info_api import MachineInfoApi  # noqa: E501
from swagger_client.rest import ApiException


class TestMachineInfoApi(unittest.TestCase):
    """MachineInfoApi unit test stubs"""

    def setUp(self):
        self.api = MachineInfoApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_all_machines(self):
        """Test case for get_all_machines

        Get status for all machines  # noqa: E501
        """
        pass

    def test_get_machine(self):
        """Test case for get_machine

        Get status for a single machine  # noqa: E501
        """
        pass

    def test_vibe_check(self):
        """Test case for vibe_check

        Get the overall vibe  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
