# coding: utf-8

"""
    Machine status API

    Helps to track status of networked machines.  # noqa: E501

    OpenAPI spec version: 0.1
    Contact: awball@polarweasel.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.disk_free_free_space import DiskFreeFreeSpace  # noqa: E501
from swagger_client.rest import ApiException


class TestDiskFreeFreeSpace(unittest.TestCase):
    """DiskFreeFreeSpace unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDiskFreeFreeSpace(self):
        """Test DiskFreeFreeSpace"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.disk_free_free_space.DiskFreeFreeSpace()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
